version: '3'

services:
  postgres:
    image: postgres:14
    container_name: ecomm_db
    environment:
      POSTGRES_DB: ecomm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
